services:
  shlink:
    image: ghcr.io/shlinkio/shlink:stable
    env_file:
      - .env
    restart: unless-stopped
  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      interval: 5s
      retries: 10
    restart: unless-stopped
  front:
    build:
      context: ./kakaku_front
      #dockerfile: ./kakaku_front/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react_app_env.json:/srv/react_app_env.json
      - ./Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - .env
    depends_on:
      - back
      - shlink
    restart: unless-stopped
  back:
    build:
      context: ./kakaku_api
      #dockerfile: ./kakaku_api/Dockerfile
    volumes:
      - ./.env:/app/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  scraping:
    build:
      context: ./kakaku_database
      #dockerfile: ./kakaku_database/Dockerfile
    volumes:
      - ./.env:/app/.env
      - ./crontab:/etc/crontab
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
      