//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "motherboard")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_id: String,
    pub name: String,
    pub price: i32,
    pub popular_rank: Option<i32>,
    pub maker_name: String,
    pub product_name: String,
    pub chipset: String,
    pub socket_name: String,
    pub form_factor: String,
    pub memory_type: String,
    pub memory_slot_count: i32,
    pub max_memory_capacity: i32,
    pub pci_slot_count: i32,
    pub pcie_x16_slot_count: i32,
    pub pcie_x8_slot_count: i32,
    pub pcie_x4_slot_count: i32,
    pub pcie_x1_slot_count: i32,
    pub sata_connector_count: i32,
    pub release_date: Option<Date>,
    //#[sea_orm(column_type = "Custom(\"BIT(1)\".to_owned())")]
    pub is_exist: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
