//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cpu_cooler_socket")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cpu_cooler_item_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub socket_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cpu_cooler::Entity",
        from = "Column::CpuCoolerItemId",
        to = "super::cpu_cooler::Column::ItemId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CpuCooler,
}

impl Related<super::cpu_cooler::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CpuCooler.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
