//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gpu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_id: String,
    pub name: String,
    pub price: i32,
    pub popular_rank: Option<i32>,
    pub maker_name: String,
    pub product_name: String,
    pub chip_name: String,
    pub gpu_memory_type: String,
    pub gpu_memory_capacity: i32,
    pub gpu_memory_bus_width: Option<i32>,
    pub gpu_memory_clock: Option<f64>,
    pub pcie_interface: String,
    //#[sea_orm(column_type = "Custom(\"BIT(1)\".to_owned())")]
    pub is_low_profile: bool,
    pub cooling_solution: String,
    pub tdp: Option<i32>,
    pub hdmi_count: i32,
    pub displayport_count: i32,
    pub width: Option<f64>,
    pub height: Option<f64>,
    pub depth: Option<f64>,
    pub radiator_width: Option<f64>,
    pub radiator_height: Option<f64>,
    pub radiator_depth: Option<f64>,
    pub release_date: Option<Date>,
    //#[sea_orm(column_type = "Custom(\"BIT(1)\".to_owned())")]
    pub is_exist: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
