//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

pub use super::case::Entity as Case;
pub use super::case_support_form_factor::Entity as CaseSupportFormFactor;
pub use super::cpu::Entity as Cpu;
pub use super::cpu_cooler::Entity as CpuCooler;
pub use super::cpu_cooler_socket::Entity as CpuCoolerSocket;
pub use super::gpu::Entity as Gpu;
pub use super::hdd::Entity as Hdd;
pub use super::memory::Entity as Memory;
pub use super::motherboard::Entity as Motherboard;
pub use super::power_supply::Entity as PowerSupply;
pub use super::ssd::Entity as Ssd;
