import Box from '@mui/material/Box';
import { useEffect, useState } from 'react';
import { Paper } from '@mui/material';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import Typography from '@mui/material/Typography';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ListSubheader from '@mui/material/ListSubheader';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Collapse from '@mui/material/Collapse';
import InboxIcon from '@mui/icons-material/MoveToInbox';
import DraftsIcon from '@mui/icons-material/Drafts';
import SendIcon from '@mui/icons-material/Send';
import ExpandLess from '@mui/icons-material/ExpandLess';
import ExpandMore from '@mui/icons-material/ExpandMore';
import StarBorder from '@mui/icons-material/StarBorder';
import IconButton from '@mui/material/IconButton';
import { Add, Remove, Delete } from '@mui/icons-material';
import Stack from '@mui/material/Stack';
import Grid from '@mui/material/Unstable_Grid2/Grid2';
import Button from '@mui/material/Button';
import CpuSelectedRow from './cpuSelectedRow';
import Divider from '@mui/material/Divider';

const CpuPriceDisplay = () => {
    const [open, setOpen] = useState(true);
    const handleClick = () => {
        setOpen(!open);
    };
    const [cpuDescriptions, setCpuDescriptions] = useState<CpuDescription[]>([
        {
            item_id: "hoge",
            name: "aaaaaa",
            base_clock: 1.0,
            boost_clock: 1.5,
            core_count: 6,
            generation: "第114514世代",
            graphics: "iGPU",
            is_exist: true,
            maker_name: "fuga",
            popular_rank: 114,
            price: 514,
            product_name: "hogehoge",
            release_date: null,
            socket_name: "364364",
            tdp: null,
            thread_count: 32
        },
        {
            item_id: "hoge",
            name: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            base_clock: 1.0,
            boost_clock: 1.5,
            core_count: 6,
            generation: "第114514世代",
            graphics: "iGPU",
            is_exist: true,
            maker_name: "fuga",
            popular_rank: 114,
            price: 514,
            product_name: "hogehoge",
            release_date: null,
            socket_name: "364364",
            tdp: null,
            thread_count: 32
        },
    ]);
    return (
        <Box sx={{ width: "100%" }}>
            <ListItemButton onClick={handleClick}>
                <ListItemText primary="Cpu" />
                {open ? <ExpandLess /> : <ExpandMore />}
            </ListItemButton>
            <Collapse in={open} timeout="auto" unmountOnExit sx={{ width: '100%' }}>
                <Stack spacing={0} sx={{ alignItems: "center", justifyItems: "center" }}>
                    <Divider />
                    {cpuDescriptions.map((cpuDescription) =>
                        <CpuSelectedRow CpuDescription={cpuDescription} />
                    )}
                </Stack>
                <Divider sx={{ paddingTop: 2 }} />
                <Button sx={{ padding: 1 }} fullWidth >新しいCPUを追加...</Button>
            </Collapse>
        </Box>
    );
}

export default CpuPriceDisplay;

export type CpuDescription = {
    // Generated by https://quicktype.io
    item_id: string;
    name: string;
    price: number;
    popular_rank: number | null;
    maker_name: string;
    product_name: string;
    generation: string;
    socket_name: string;
    core_count: number;
    thread_count: number;
    tdp: number | null;
    base_clock: number;
    boost_clock: number | null;
    graphics: string;
    release_date: Date | null;
    is_exist: boolean;
};