name: Build container images
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    # 複数のDockerfileが配置されたディレクトリを列挙
    strategy:
      matrix:
        target: ["kakaku_api", "kakaku_database", "kakaku_front"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 並列でContainer Imageをビルド
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.target }}
          push: true
          tags: ghcr.io/tky2240/${{ matrix.target }}:${{ github.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
